// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  LL-GAME
// DateTime: 12/12/2025 12:47:25 AM
// UserName: LaughingLeader
// Input file <C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy - 12/11/2025 11:26:13 PM>

// options: lines

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace LSLib.Stats.StatParser;

public enum StatTokens
{
	error = 46, EOF = 47, NEW = 48,
	ADD = 49, ENTRY = 50, TYPE = 51, DATA = 52, PARAM = 53, USING = 54,
	KEY = 55, ABILITY = 56, ITEMCOLOR = 57, NAMEGROUP = 58, NAME = 59, NAMECOOL = 60,
	ITEMGROUP = 61, LEVELGROUP = 62, ROOTGROUP = 63, REQUIREMENT = 64, DELTAMOD = 65, NEW_BOOST = 66,
	EQUIPMENT = 67, ADD_EQUIPMENTGROUP = 68, ADD_EQUIPMENT_ENTRY = 69, ITEMCOMBOPROPERTY = 70, NEW_ITEMCOMBOPROPERTYENTRY = 71, ITEM_COMBINATION = 72,
	ITEM_COMBINATION_RESULT = 73, CRAFTING_PREVIEW_DATA = 74, SKILLSET = 75, SKILL = 76, CATEGORY_MAP = 77, WEAPON_COUNTER = 78,
	SKILLBOOK_COUNTER = 79, ARMOR_COUNTER = 80, TREASURE = 81, ITEMTYPES = 82, TREASURE_TABLE = 83, NEW_SUBTABLE = 84,
	OBJECT_CATEGORY = 85, START_LEVEL = 86, END_LEVEL = 87, MIN_LEVEL = 88, MAX_LEVEL = 89, CAN_MERGE = 90,
	IGNORE_LEVEL_DIFF = 91, USE_TREASURE_GROUPS = 92, BAD = 93, INTEGER = 94, STRING = 95, DATA_ITEM = 96
};

[GeneratedCodeAttribute("Gardens Point Parser Generator", "1.5.2")]
public partial class StatParser : ShiftReduceParser<System.Object, LSLib.Parser.CodeLocation>
{
#pragma warning disable 649
	private static Dictionary<int, string> aliases;
#pragma warning restore 649
	private static Rule[] rules = new Rule[103];
	private static State[] states = new State[225];
	private static string[] nonTerms = new string[] {
	  "StatFile", "$accept", "Declarations", "Declaration", "TreasureTypesDeclaration",
	  "DataDeclaration", "EntryHeader", "EntryProperties", "EntryProperty", "EntryStdHeader",
	  "DataKeyHeader", "AbilityHeader", "RequirementsHeader", "DeltaModHeader",
	  "ItemColorHeader", "ItemCombinationHeader", "ItemCombinationResultHeader",
	  "ItemProgressionNamesHeader", "ItemProgressionVisualsHeader", "EquipmentHeader",
	  "ItemComboPropertyHeader", "ObjectCategoryItemComboPreviewDataHeader",
	  "SkillSetHeader", "TreasureGroupHeader", "TreasureTableHeader", "EntryType",
	  "EntryUsing", "EntryData", "EntryDataHack", "EntryParam", "ItemProgressionName",
	  "ItemProgressionNameCool", "ItemProgressionVisualLevel", "ItemProgressionVisualName",
	  "ItemProgressionVisualRoot", "DeltaModifierBoost", "EquipmentGroup", "ItemComboPropertyEntry",
	  "SkillSetSkill", "TreasureGroupWeaponCounter", "TreasureGroupSkillbookCounter",
	  "TreasureGroupArmorCounter", "TreasureSubtable", "TreasureTableMinLevel",
	  "TreasureTableMaxLevel", "TreasureTableCanMerge", "TreasureTableIgnoreLevelDiff",
	  "TreasureTableUseTreasureGroups", "EquipmentEntries", "EquipmentEntry",
	  "EntrySubProperties", "TreasureTableObjects", "TreasureTableEntry", "TreasureTableObject",
	  "TreasureTableObjectStartLevel", "TreasureTableObjectEndLevel", };

	static StatParser()
	{
		states[0] = new State(-3, new int[] { -1, 1, -3, 3 });
		states[1] = new State(new int[] { 47, 2 });
		states[2] = new State(-1);
		states[3] = new State(new int[] { 48, 136, 55, 168, 56, 173, 64, 190, 77, 205, 81, 210, 47, -2 }, new int[] { -4, 4, -5, 5, -6, 6, -7, 7, -10, 135, -11, 167, -12, 172, -13, 189, -14, 194, -15, 195, -16, 196, -17, 197, -18, 198, -19, 199, -20, 200, -21, 201, -22, 202, -23, 203, -24, 204, -25, 209 });
		states[4] = new State(-4);
		states[5] = new State(-5);
		states[6] = new State(-7);
		states[7] = new State(-9, new int[] { -8, 8 });
		states[8] = new State(new int[] { 51, 11, 54, 14, 52, 17, 96, 21, 53, 23, 49, 27, 66, 59, 68, 64, 71, 70, 78, 75, 79, 80, 80, 85, 84, 90, 88, 120, 89, 123, 90, 126, 91, 130, 92, 133, 48, -8, 55, -8, 56, -8, 64, -8, 77, -8, 81, -8, 47, -8 }, new int[] { -9, 9, -26, 10, -27, 13, -28, 16, -29, 20, -30, 22, -31, 26, -32, 54, -33, 55, -34, 56, -35, 57, -36, 58, -37, 63, -38, 69, -39, 73, -40, 74, -41, 79, -42, 84, -43, 89, -44, 119, -45, 122, -46, 125, -47, 129, -48, 132 });
		states[9] = new State(-10);
		states[10] = new State(-43);
		states[11] = new State(new int[] { 95, 12 });
		states[12] = new State(-66);
		states[13] = new State(-44);
		states[14] = new State(new int[] { 95, 15 });
		states[15] = new State(-67);
		states[16] = new State(-45);
		states[17] = new State(new int[] { 95, 18 });
		states[18] = new State(new int[] { 95, 19 });
		states[19] = new State(-68);
		states[20] = new State(-46);
		states[21] = new State(-69);
		states[22] = new State(-47);
		states[23] = new State(new int[] { 95, 24 });
		states[24] = new State(new int[] { 95, 25 });
		states[25] = new State(-70);
		states[26] = new State(-48);
		states[27] = new State(new int[] { 59, 28, 60, 32, 62, 36, 63, 42, 58, 46, 76, 52 });
		states[28] = new State(new int[] { 95, 29 });
		states[29] = new State(new int[] { 44, 30 });
		states[30] = new State(new int[] { 95, 31 });
		states[31] = new State(-71);
		states[32] = new State(new int[] { 95, 33 });
		states[33] = new State(new int[] { 44, 34 });
		states[34] = new State(new int[] { 95, 35 });
		states[35] = new State(-72);
		states[36] = new State(new int[] { 94, 37 });
		states[37] = new State(new int[] { 44, 38 });
		states[38] = new State(new int[] { 94, 39 });
		states[39] = new State(new int[] { 44, 40 });
		states[40] = new State(new int[] { 95, 41 });
		states[41] = new State(-73);
		states[42] = new State(new int[] { 95, 43 });
		states[43] = new State(new int[] { 44, 44 });
		states[44] = new State(new int[] { 95, 45 });
		states[45] = new State(-74);
		states[46] = new State(new int[] { 95, 47 });
		states[47] = new State(new int[] { 44, 48 });
		states[48] = new State(new int[] { 95, 49 });
		states[49] = new State(new int[] { 44, 50 });
		states[50] = new State(new int[] { 95, 51 });
		states[51] = new State(-75);
		states[52] = new State(new int[] { 95, 53 });
		states[53] = new State(-84);
		states[54] = new State(-49);
		states[55] = new State(-50);
		states[56] = new State(-51);
		states[57] = new State(-52);
		states[58] = new State(-53);
		states[59] = new State(new int[] { 95, 60 });
		states[60] = new State(new int[] { 44, 61 });
		states[61] = new State(new int[] { 94, 62 });
		states[62] = new State(-76);
		states[63] = new State(-54);
		states[64] = new State(-78, new int[] { -49, 65 });
		states[65] = new State(new int[] { 69, 67, 51, -77, 54, -77, 52, -77, 96, -77, 53, -77, 49, -77, 66, -77, 68, -77, 71, -77, 78, -77, 79, -77, 80, -77, 84, -77, 88, -77, 89, -77, 90, -77, 91, -77, 92, -77, 48, -77, 55, -77, 56, -77, 64, -77, 77, -77, 81, -77, 47, -77 }, new int[] { -50, 66 });
		states[66] = new State(-79);
		states[67] = new State(new int[] { 95, 68 });
		states[68] = new State(-80);
		states[69] = new State(-55);
		states[70] = new State(-82, new int[] { -51, 71 });
		states[71] = new State(new int[] { 52, 17, 51, -81, 54, -81, 96, -81, 53, -81, 49, -81, 66, -81, 68, -81, 71, -81, 78, -81, 79, -81, 80, -81, 84, -81, 88, -81, 89, -81, 90, -81, 91, -81, 92, -81, 48, -81, 55, -81, 56, -81, 64, -81, 77, -81, 81, -81, 47, -81 }, new int[] { -28, 72 });
		states[72] = new State(-83);
		states[73] = new State(-56);
		states[74] = new State(-57);
		states[75] = new State(new int[] { 95, 76 });
		states[76] = new State(new int[] { 44, 77 });
		states[77] = new State(new int[] { 95, 78 });
		states[78] = new State(-85);
		states[79] = new State(-58);
		states[80] = new State(new int[] { 95, 81 });
		states[81] = new State(new int[] { 44, 82 });
		states[82] = new State(new int[] { 95, 83 });
		states[83] = new State(-86);
		states[84] = new State(-59);
		states[85] = new State(new int[] { 95, 86 });
		states[86] = new State(new int[] { 44, 87 });
		states[87] = new State(new int[] { 95, 88 });
		states[88] = new State(-87);
		states[89] = new State(-60);
		states[90] = new State(new int[] { 95, 91 });
		states[91] = new State(-95, new int[] { -52, 92 });
		states[92] = new State(new int[] { 85, 95, 86, 114, 87, 117, 51, -88, 54, -88, 52, -88, 96, -88, 53, -88, 49, -88, 66, -88, 68, -88, 71, -88, 78, -88, 79, -88, 80, -88, 84, -88, 88, -88, 89, -88, 90, -88, 91, -88, 92, -88, 48, -88, 55, -88, 56, -88, 64, -88, 77, -88, 81, -88, 47, -88 }, new int[] { -53, 93, -54, 94, -55, 113, -56, 116 });
		states[93] = new State(-96);
		states[94] = new State(-97);
		states[95] = new State(new int[] { 95, 96 });
		states[96] = new State(new int[] { 44, 97 });
		states[97] = new State(new int[] { 94, 98 });
		states[98] = new State(new int[] { 44, 99 });
		states[99] = new State(new int[] { 94, 100 });
		states[100] = new State(new int[] { 44, 101 });
		states[101] = new State(new int[] { 94, 102 });
		states[102] = new State(new int[] { 44, 103 });
		states[103] = new State(new int[] { 94, 104 });
		states[104] = new State(new int[] { 44, 105 });
		states[105] = new State(new int[] { 94, 106 });
		states[106] = new State(new int[] { 44, 107 });
		states[107] = new State(new int[] { 94, 108 });
		states[108] = new State(new int[] { 44, 109 });
		states[109] = new State(new int[] { 94, 110 });
		states[110] = new State(new int[] { 44, 111 });
		states[111] = new State(new int[] { 94, 112 });
		states[112] = new State(-102);
		states[113] = new State(-98);
		states[114] = new State(new int[] { 95, 115 });
		states[115] = new State(-100);
		states[116] = new State(-99);
		states[117] = new State(new int[] { 95, 118 });
		states[118] = new State(-101);
		states[119] = new State(-61);
		states[120] = new State(new int[] { 95, 121 });
		states[121] = new State(-89);
		states[122] = new State(-62);
		states[123] = new State(new int[] { 95, 124 });
		states[124] = new State(-90);
		states[125] = new State(-63);
		states[126] = new State(new int[] { 95, 127, 94, 128 });
		states[127] = new State(-91);
		states[128] = new State(-92);
		states[129] = new State(-64);
		states[130] = new State(new int[] { 94, 131 });
		states[131] = new State(-93);
		states[132] = new State(-65);
		states[133] = new State(new int[] { 94, 134 });
		states[134] = new State(-94);
		states[135] = new State(-11);
		states[136] = new State(new int[] { 50, 137, 65, 139, 57, 141, 72, 149, 73, 151, 58, 153, 61, 155, 67, 157, 70, 159, 74, 161, 75, 163, 83, 165 });
		states[137] = new State(new int[] { 95, 138 });
		states[138] = new State(-27);
		states[139] = new State(new int[] { 95, 140 });
		states[140] = new State(-31);
		states[141] = new State(new int[] { 95, 142 });
		states[142] = new State(new int[] { 44, 143 });
		states[143] = new State(new int[] { 95, 144 });
		states[144] = new State(new int[] { 44, 145 });
		states[145] = new State(new int[] { 95, 146 });
		states[146] = new State(new int[] { 44, 147 });
		states[147] = new State(new int[] { 95, 148 });
		states[148] = new State(-34);
		states[149] = new State(new int[] { 95, 150 });
		states[150] = new State(-32);
		states[151] = new State(new int[] { 95, 152 });
		states[152] = new State(-33);
		states[153] = new State(new int[] { 95, 154 });
		states[154] = new State(-35);
		states[155] = new State(new int[] { 95, 156 });
		states[156] = new State(-36);
		states[157] = new State(new int[] { 95, 158 });
		states[158] = new State(-37);
		states[159] = new State(new int[] { 95, 160 });
		states[160] = new State(-38);
		states[161] = new State(new int[] { 95, 162 });
		states[162] = new State(-39);
		states[163] = new State(new int[] { 95, 164 });
		states[164] = new State(-40);
		states[165] = new State(new int[] { 95, 166 });
		states[166] = new State(-42);
		states[167] = new State(-12);
		states[168] = new State(new int[] { 95, 169 });
		states[169] = new State(new int[] { 44, 170 });
		states[170] = new State(new int[] { 95, 171 });
		states[171] = new State(-28);
		states[172] = new State(-13);
		states[173] = new State(new int[] { 59, 174 });
		states[174] = new State(new int[] { 44, 175 });
		states[175] = new State(new int[] { 94, 176 });
		states[176] = new State(new int[] { 44, 177 });
		states[177] = new State(new int[] { 94, 178 });
		states[178] = new State(new int[] { 44, 179 });
		states[179] = new State(new int[] { 94, 180 });
		states[180] = new State(new int[] { 44, 181 });
		states[181] = new State(new int[] { 94, 182 });
		states[182] = new State(new int[] { 44, 183 });
		states[183] = new State(new int[] { 94, 184 });
		states[184] = new State(new int[] { 44, 185 });
		states[185] = new State(new int[] { 94, 186 });
		states[186] = new State(new int[] { 44, 187 });
		states[187] = new State(new int[] { 94, 188 });
		states[188] = new State(-29);
		states[189] = new State(-14);
		states[190] = new State(new int[] { 95, 191 });
		states[191] = new State(new int[] { 44, 192 });
		states[192] = new State(new int[] { 95, 193 });
		states[193] = new State(-30);
		states[194] = new State(-15);
		states[195] = new State(-16);
		states[196] = new State(-17);
		states[197] = new State(-18);
		states[198] = new State(-19);
		states[199] = new State(-20);
		states[200] = new State(-21);
		states[201] = new State(-22);
		states[202] = new State(-23);
		states[203] = new State(-24);
		states[204] = new State(-25);
		states[205] = new State(new int[] { 95, 206 });
		states[206] = new State(new int[] { 44, 207 });
		states[207] = new State(new int[] { 95, 208 });
		states[208] = new State(-41);
		states[209] = new State(-26);
		states[210] = new State(new int[] { 82, 211 });
		states[211] = new State(new int[] { 95, 212 });
		states[212] = new State(new int[] { 44, 213 });
		states[213] = new State(new int[] { 95, 214 });
		states[214] = new State(new int[] { 44, 215 });
		states[215] = new State(new int[] { 95, 216 });
		states[216] = new State(new int[] { 44, 217 });
		states[217] = new State(new int[] { 95, 218 });
		states[218] = new State(new int[] { 44, 219 });
		states[219] = new State(new int[] { 95, 220 });
		states[220] = new State(new int[] { 44, 221 });
		states[221] = new State(new int[] { 95, 222 });
		states[222] = new State(new int[] { 44, 223 });
		states[223] = new State(new int[] { 95, 224 });
		states[224] = new State(-6);

		for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

		rules[1] = new Rule(-2, new int[] { -1, 47 });
		rules[2] = new Rule(-1, new int[] { -3 });
		rules[3] = new Rule(-3, new int[] { });
		rules[4] = new Rule(-3, new int[] { -3, -4 });
		rules[5] = new Rule(-3, new int[] { -3, -5 });
		rules[6] = new Rule(-5, new int[] { 81, 82, 95, 44, 95, 44, 95, 44, 95, 44, 95, 44, 95, 44, 95 });
		rules[7] = new Rule(-4, new int[] { -6 });
		rules[8] = new Rule(-6, new int[] { -7, -8 });
		rules[9] = new Rule(-8, new int[] { });
		rules[10] = new Rule(-8, new int[] { -8, -9 });
		rules[11] = new Rule(-7, new int[] { -10 });
		rules[12] = new Rule(-7, new int[] { -11 });
		rules[13] = new Rule(-7, new int[] { -12 });
		rules[14] = new Rule(-7, new int[] { -13 });
		rules[15] = new Rule(-7, new int[] { -14 });
		rules[16] = new Rule(-7, new int[] { -15 });
		rules[17] = new Rule(-7, new int[] { -16 });
		rules[18] = new Rule(-7, new int[] { -17 });
		rules[19] = new Rule(-7, new int[] { -18 });
		rules[20] = new Rule(-7, new int[] { -19 });
		rules[21] = new Rule(-7, new int[] { -20 });
		rules[22] = new Rule(-7, new int[] { -21 });
		rules[23] = new Rule(-7, new int[] { -22 });
		rules[24] = new Rule(-7, new int[] { -23 });
		rules[25] = new Rule(-7, new int[] { -24 });
		rules[26] = new Rule(-7, new int[] { -25 });
		rules[27] = new Rule(-10, new int[] { 48, 50, 95 });
		rules[28] = new Rule(-11, new int[] { 55, 95, 44, 95 });
		rules[29] = new Rule(-12, new int[] { 56, 59, 44, 94, 44, 94, 44, 94, 44, 94, 44, 94, 44, 94, 44, 94 });
		rules[30] = new Rule(-13, new int[] { 64, 95, 44, 95 });
		rules[31] = new Rule(-14, new int[] { 48, 65, 95 });
		rules[32] = new Rule(-16, new int[] { 48, 72, 95 });
		rules[33] = new Rule(-17, new int[] { 48, 73, 95 });
		rules[34] = new Rule(-15, new int[] { 48, 57, 95, 44, 95, 44, 95, 44, 95 });
		rules[35] = new Rule(-18, new int[] { 48, 58, 95 });
		rules[36] = new Rule(-19, new int[] { 48, 61, 95 });
		rules[37] = new Rule(-20, new int[] { 48, 67, 95 });
		rules[38] = new Rule(-21, new int[] { 48, 70, 95 });
		rules[39] = new Rule(-22, new int[] { 48, 74, 95 });
		rules[40] = new Rule(-23, new int[] { 48, 75, 95 });
		rules[41] = new Rule(-24, new int[] { 77, 95, 44, 95 });
		rules[42] = new Rule(-25, new int[] { 48, 83, 95 });
		rules[43] = new Rule(-9, new int[] { -26 });
		rules[44] = new Rule(-9, new int[] { -27 });
		rules[45] = new Rule(-9, new int[] { -28 });
		rules[46] = new Rule(-9, new int[] { -29 });
		rules[47] = new Rule(-9, new int[] { -30 });
		rules[48] = new Rule(-9, new int[] { -31 });
		rules[49] = new Rule(-9, new int[] { -32 });
		rules[50] = new Rule(-9, new int[] { -33 });
		rules[51] = new Rule(-9, new int[] { -34 });
		rules[52] = new Rule(-9, new int[] { -35 });
		rules[53] = new Rule(-9, new int[] { -36 });
		rules[54] = new Rule(-9, new int[] { -37 });
		rules[55] = new Rule(-9, new int[] { -38 });
		rules[56] = new Rule(-9, new int[] { -39 });
		rules[57] = new Rule(-9, new int[] { -40 });
		rules[58] = new Rule(-9, new int[] { -41 });
		rules[59] = new Rule(-9, new int[] { -42 });
		rules[60] = new Rule(-9, new int[] { -43 });
		rules[61] = new Rule(-9, new int[] { -44 });
		rules[62] = new Rule(-9, new int[] { -45 });
		rules[63] = new Rule(-9, new int[] { -46 });
		rules[64] = new Rule(-9, new int[] { -47 });
		rules[65] = new Rule(-9, new int[] { -48 });
		rules[66] = new Rule(-26, new int[] { 51, 95 });
		rules[67] = new Rule(-27, new int[] { 54, 95 });
		rules[68] = new Rule(-28, new int[] { 52, 95, 95 });
		rules[69] = new Rule(-29, new int[] { 96 });
		rules[70] = new Rule(-30, new int[] { 53, 95, 95 });
		rules[71] = new Rule(-31, new int[] { 49, 59, 95, 44, 95 });
		rules[72] = new Rule(-32, new int[] { 49, 60, 95, 44, 95 });
		rules[73] = new Rule(-33, new int[] { 49, 62, 94, 44, 94, 44, 95 });
		rules[74] = new Rule(-34, new int[] { 49, 63, 95, 44, 95 });
		rules[75] = new Rule(-35, new int[] { 49, 58, 95, 44, 95, 44, 95 });
		rules[76] = new Rule(-36, new int[] { 66, 95, 44, 94 });
		rules[77] = new Rule(-37, new int[] { 68, -49 });
		rules[78] = new Rule(-49, new int[] { });
		rules[79] = new Rule(-49, new int[] { -49, -50 });
		rules[80] = new Rule(-50, new int[] { 69, 95 });
		rules[81] = new Rule(-38, new int[] { 71, -51 });
		rules[82] = new Rule(-51, new int[] { });
		rules[83] = new Rule(-51, new int[] { -51, -28 });
		rules[84] = new Rule(-39, new int[] { 49, 76, 95 });
		rules[85] = new Rule(-40, new int[] { 78, 95, 44, 95 });
		rules[86] = new Rule(-41, new int[] { 79, 95, 44, 95 });
		rules[87] = new Rule(-42, new int[] { 80, 95, 44, 95 });
		rules[88] = new Rule(-43, new int[] { 84, 95, -52 });
		rules[89] = new Rule(-44, new int[] { 88, 95 });
		rules[90] = new Rule(-45, new int[] { 89, 95 });
		rules[91] = new Rule(-46, new int[] { 90, 95 });
		rules[92] = new Rule(-46, new int[] { 90, 94 });
		rules[93] = new Rule(-47, new int[] { 91, 94 });
		rules[94] = new Rule(-48, new int[] { 92, 94 });
		rules[95] = new Rule(-52, new int[] { });
		rules[96] = new Rule(-52, new int[] { -52, -53 });
		rules[97] = new Rule(-53, new int[] { -54 });
		rules[98] = new Rule(-53, new int[] { -55 });
		rules[99] = new Rule(-53, new int[] { -56 });
		rules[100] = new Rule(-55, new int[] { 86, 95 });
		rules[101] = new Rule(-56, new int[] { 87, 95 });
		rules[102] = new Rule(-54, new int[] { 85, 95, 44, 94, 44, 94, 44, 94, 44, 94, 44, 94, 44, 94, 44, 94, 44, 94 });
	}

	protected override void Initialize()
	{
		this.InitSpecialTokens((int)StatTokens.error, (int)StatTokens.EOF);
		this.InitStates(states);
		this.InitRules(rules);
		this.InitNonTerminals(nonTerms);
	}

	protected override void DoAction(int action)
	{
#pragma warning disable 162, 1522
		switch (action)
		{
			case 3: // Declarations -> /* empty */
#line 99 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeDeclarationList(); }
#line default
				break;
			case 4: // Declarations -> Declarations, Declaration
#line 100 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = AddDeclaration(ValueStack[ValueStack.Depth - 2], ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 5: // Declarations -> Declarations, TreasureTypesDeclaration
#line 101 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = ValueStack[ValueStack.Depth - 2]; }
#line default
				break;
			case 8: // DataDeclaration -> EntryHeader, EntryProperties
#line 108 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = AddProperty(ValueStack[ValueStack.Depth - 1], ValueStack[ValueStack.Depth - 2]); }
#line default
				break;
			case 9: // EntryProperties -> /* empty */
#line 110 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan); }
#line default
				break;
			case 10: // EntryProperties -> EntryProperties, EntryProperty
#line 111 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = AddProperty(ValueStack[ValueStack.Depth - 2], ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 27: // EntryStdHeader -> NEW, ENTRY, STRING
#line 131 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(LocationStack[LocationStack.Depth - 1], "Name", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 28: // DataKeyHeader -> KEY, STRING, ',', STRING
#line 134 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-3], "Key", ValueStack[ValueStack.Depth-3]),
				MakeProperty("EntityType", "Data"),
				MakeProperty(LocationStack[LocationStack.Depth-1], "Value", ValueStack[ValueStack.Depth-1])
			});
				}
#line default
				break;
			case 29: // AbilityHeader -> ABILITY, NAME, ',', INTEGER, ',', INTEGER, ',', INTEGER, ',', 
					 //                  INTEGER, ',', INTEGER, ',', INTEGER, ',', INTEGER
#line 142 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-15], "Name", ValueStack[ValueStack.Depth-15]),
				MakeProperty("EntityType", "Ability")
			});
				}
#line default
				break;
			case 30: // RequirementsHeader -> REQUIREMENT, STRING, ',', STRING
#line 148 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-3], "Name", ValueStack[ValueStack.Depth-3]),
				MakeProperty("EntityType", "Requirement"),
				MakeProperty(LocationStack[LocationStack.Depth-1], "Requirements", ValueStack[ValueStack.Depth-1])
			});
				}
#line default
				break;
			case 31: // DeltaModHeader -> NEW, DELTAMOD, STRING
#line 155 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "DeltaModifier")
			});
				}
#line default
				break;
			case 32: // ItemCombinationHeader -> NEW, ITEM_COMBINATION, STRING
#line 161 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "ItemCombination")
			});
				}
#line default
				break;
			case 33: // ItemCombinationResultHeader -> NEW, ITEM_COMBINATION_RESULT, STRING
#line 167 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "ItemCombinationResult")
			});
				}
#line default
				break;
			case 34: // ItemColorHeader -> NEW, ITEMCOLOR, STRING, ',', STRING, ',', STRING, ',', 
					 //                    STRING
#line 173 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-7], "ItemColorName", ValueStack[ValueStack.Depth-7]),
				MakeProperty("EntityType", "ItemColor"),
				MakeProperty(LocationStack[LocationStack.Depth-5], "Primary Color", ValueStack[ValueStack.Depth-5]),
				MakeProperty(LocationStack[LocationStack.Depth-3], "Secondary Color", ValueStack[ValueStack.Depth-3]),
				MakeProperty(LocationStack[LocationStack.Depth-1], "Tertiary Color", ValueStack[ValueStack.Depth-1]),
			});
				}
#line default
				break;
			case 35: // ItemProgressionNamesHeader -> NEW, NAMEGROUP, STRING
#line 182 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "ItemProgressionNames")
			});
				}
#line default
				break;
			case 36: // ItemProgressionVisualsHeader -> NEW, ITEMGROUP, STRING
#line 188 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "ItemProgressionVisuals")
			});
				}
#line default
				break;
			case 37: // EquipmentHeader -> NEW, EQUIPMENT, STRING
#line 194 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "Equipment")
			});
				}
#line default
				break;
			case 38: // ItemComboPropertyHeader -> NEW, ITEMCOMBOPROPERTY, STRING
#line 200 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "ItemComboProperties")
			});
				}
#line default
				break;
			case 39: // ObjectCategoryItemComboPreviewDataHeader -> NEW, CRAFTING_PREVIEW_DATA, STRING
#line 206 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1])
			});
				}
#line default
				break;
			case 40: // SkillSetHeader -> NEW, SKILLSET, STRING
#line 211 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-1], "Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "SkillSet")
			});
				}
#line default
				break;
			case 41: // TreasureGroupHeader -> CATEGORY_MAP, STRING, ',', STRING
#line 217 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-3], "Name", ValueStack[ValueStack.Depth-3]),
				MakeProperty(LocationStack[LocationStack.Depth-1], "TreasureGroup", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "TreasureGroups")
			});
				}
#line default
				break;
			case 42: // TreasureTableHeader -> NEW, TREASURE_TABLE, STRING
#line 224 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty("Name", ValueStack[ValueStack.Depth-1]),
				MakeProperty("EntityType", "TreasureTable")
			});
				}
#line default
				break;
			case 66: // EntryType -> TYPE, STRING
#line 254 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "EntityType", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 67: // EntryUsing -> USING, STRING
#line 256 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "Using", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 68: // EntryData -> DATA, STRING, STRING
#line 258 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, ValueStack[ValueStack.Depth - 2], ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 70: // EntryParam -> PARAM, STRING, STRING
#line 262 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, ValueStack[ValueStack.Depth - 2], ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 71: // ItemProgressionName -> ADD, NAME, STRING, ',', STRING
#line 265 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeElement("Names", new Dictionary<String, object> {
					{"Name", Unwrap(ValueStack[ValueStack.Depth-3])},
					{"Description", Unwrap(ValueStack[ValueStack.Depth-1])}
			});
				}
#line default
				break;
			case 72: // ItemProgressionNameCool -> ADD, NAMECOOL, STRING, ',', STRING
#line 271 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeElement("NamesCool", new Dictionary<String, object> {
					{"Name", Unwrap(ValueStack[ValueStack.Depth-3])},
					{"Description", Unwrap(ValueStack[ValueStack.Depth-1])}
			});
				}
#line default
				break;
			case 73: // ItemProgressionVisualLevel -> ADD, LEVELGROUP, INTEGER, ',', INTEGER, ',', 
					 //                               STRING
#line 277 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeElement("LevelGroups", new Dictionary<String, object> {
					{"MinLevel", Unwrap(ValueStack[ValueStack.Depth-5])},
					{"MaxLevel", Unwrap(ValueStack[ValueStack.Depth-3])},
					{"Rarity", Unwrap(ValueStack[ValueStack.Depth-1])},
			});
				}
#line default
				break;
			case 74: // ItemProgressionVisualName -> ADD, ROOTGROUP, STRING, ',', STRING
#line 284 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeElement("NameGroups", new Dictionary<String, object> {
					{"RootTemplate", Unwrap(ValueStack[ValueStack.Depth-3])},
					{"ItemColor", Unwrap(ValueStack[ValueStack.Depth-1])},
			});
				}
#line default
				break;
			case 75: // ItemProgressionVisualRoot -> ADD, NAMEGROUP, STRING, ',', STRING, ',', STRING
#line 290 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeElement("RootGroups", new Dictionary<String, object> {
					{"NameGroup", Unwrap(ValueStack[ValueStack.Depth-5])},
					{"AffixType", Unwrap(ValueStack[ValueStack.Depth-3])},
					{"Icon", Unwrap(ValueStack[ValueStack.Depth-1])},
			});
				}
#line default
				break;
			case 76: // DeltaModifierBoost -> NEW_BOOST, STRING, ',', INTEGER
#line 297 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeElement("Boosts", new Dictionary<String, object> {
					{"Boost", Unwrap(ValueStack[ValueStack.Depth-3])},
					{"Multiplier", Unwrap(ValueStack[ValueStack.Depth-1])},
			});
				}
#line default
				break;
			case 77: // EquipmentGroup -> ADD_EQUIPMENTGROUP, EquipmentEntries
#line 302 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeElement("EquipmentGroups", ValueStack[ValueStack.Depth - 1], LocationStack[LocationStack.Depth - 1]); }
#line default
				break;
			case 78: // EquipmentEntries -> /* empty */
#line 304 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeCollection(); }
#line default
				break;
			case 79: // EquipmentEntries -> EquipmentEntries, EquipmentEntry
#line 305 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = AddElement(ValueStack[ValueStack.Depth - 2], ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 80: // EquipmentEntry -> ADD_EQUIPMENT_ENTRY, STRING
#line 308 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = ValueStack[ValueStack.Depth - 1]; }
#line default
				break;
			case 81: // ItemComboPropertyEntry -> NEW_ITEMCOMBOPROPERTYENTRY, EntrySubProperties
#line 310 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeElement("Entries", ValueStack[ValueStack.Depth - 1], LocationStack[LocationStack.Depth - 1]); }
#line default
				break;
			case 82: // EntrySubProperties -> /* empty */
#line 312 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeDeclaration(); }
#line default
				break;
			case 83: // EntrySubProperties -> EntrySubProperties, EntryData
#line 313 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = AddProperty(ValueStack[ValueStack.Depth - 2], ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 84: // SkillSetSkill -> ADD, SKILL, STRING
#line 316 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeElement("NameGroups", ValueStack[ValueStack.Depth - 1], LocationStack[LocationStack.Depth - 1]); }
#line default
				break;
			case 85: // TreasureGroupWeaponCounter -> WEAPON_COUNTER, STRING, ',', STRING
#line 319 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-3], "WeaponTreasureGroup", ValueStack[ValueStack.Depth-3]),
				MakeProperty(LocationStack[LocationStack.Depth-1], "WeaponDefaultCounter", ValueStack[ValueStack.Depth-1])
			});
				}
#line default
				break;
			case 86: // TreasureGroupSkillbookCounter -> SKILLBOOK_COUNTER, STRING, ',', STRING
#line 325 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-3], "SkillbookTreasureGroup", ValueStack[ValueStack.Depth-3]),
				MakeProperty(LocationStack[LocationStack.Depth-1], "SkillbookDefaultCounter", ValueStack[ValueStack.Depth-1])
			});
				}
#line default
				break;
			case 87: // TreasureGroupArmorCounter -> ARMOR_COUNTER, STRING, ',', STRING
#line 331 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-3], "ArmorTreasureGroup", ValueStack[ValueStack.Depth-3]),
				MakeProperty(LocationStack[LocationStack.Depth-1], "ArmorDefaultCounter", ValueStack[ValueStack.Depth-1])
			});
				}
#line default
				break;
			case 88: // TreasureSubtable -> NEW_SUBTABLE, STRING, TreasureTableObjects
#line 337 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeElement("Subtables",
				AddProperty(
					MakeDeclaration(CurrentLocationSpan, new[] { MakeProperty(LocationStack[LocationStack.Depth - 2], "DropCount", ValueStack[ValueStack.Depth - 2]) }),
					ValueStack[ValueStack.Depth - 1]
				), CurrentLocationSpan);
				}
#line default
				break;
			case 89: // TreasureTableMinLevel -> MIN_LEVEL, STRING
#line 344 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "MinLevel", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 90: // TreasureTableMaxLevel -> MAX_LEVEL, STRING
#line 346 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "MaxLevel", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 91: // TreasureTableCanMerge -> CAN_MERGE, STRING
#line 348 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "CanMerge", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 92: // TreasureTableCanMerge -> CAN_MERGE, INTEGER
#line 349 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "CanMerge", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 93: // TreasureTableIgnoreLevelDiff -> IGNORE_LEVEL_DIFF, INTEGER
#line 351 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "IgnoreLevelDiff", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 94: // TreasureTableUseTreasureGroups -> USE_TREASURE_GROUPS, INTEGER
#line 353 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "UseTreasureGroupCounters", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 95: // TreasureTableObjects -> /* empty */
#line 355 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeDeclaration(); }
#line default
				break;
			case 96: // TreasureTableObjects -> TreasureTableObjects, TreasureTableEntry
#line 356 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = AddProperty(ValueStack[ValueStack.Depth - 2], ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 100: // TreasureTableObjectStartLevel -> START_LEVEL, STRING
#line 364 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "StartLevel", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 101: // TreasureTableObjectEndLevel -> END_LEVEL, STRING
#line 366 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{ CurrentSemanticValue = MakeProperty(CurrentLocationSpan, "EndLevel", ValueStack[ValueStack.Depth - 1]); }
#line default
				break;
			case 102: // TreasureTableObject -> OBJECT_CATEGORY, STRING, ',', INTEGER, ',', INTEGER, ',', 
					  //                        INTEGER, ',', INTEGER, ',', INTEGER, ',', INTEGER, ',', 
					  //                        INTEGER, ',', INTEGER
#line 369 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\File\Stat.yy"
				{
					CurrentSemanticValue = MakeElement("Objects", MakeDeclaration(CurrentLocationSpan, new[] {
				MakeProperty(LocationStack[LocationStack.Depth-17], "Drop", ValueStack[ValueStack.Depth-17]),
				MakeProperty(LocationStack[LocationStack.Depth-15], "Frequency", ValueStack[ValueStack.Depth-15]),
				MakeProperty(LocationStack[LocationStack.Depth-13], "Common", ValueStack[ValueStack.Depth-13]),
				MakeProperty(LocationStack[LocationStack.Depth-11], "Uncommon", ValueStack[ValueStack.Depth-11]),
				MakeProperty(LocationStack[LocationStack.Depth-9], "Rare", ValueStack[ValueStack.Depth-9]),
				MakeProperty(LocationStack[LocationStack.Depth-7], "Epic", ValueStack[ValueStack.Depth-7]),
				MakeProperty(LocationStack[LocationStack.Depth-5], "Legendary", ValueStack[ValueStack.Depth-5]),
				MakeProperty(LocationStack[LocationStack.Depth-3], "Divine", ValueStack[ValueStack.Depth-3]),
				MakeProperty(LocationStack[LocationStack.Depth-1], "Unique", ValueStack[ValueStack.Depth-1]),
				}), CurrentLocationSpan);
				}
#line default
				break;
		}
#pragma warning restore 162, 1522
	}

	protected override string TerminalToString(int terminal)
	{
		if (aliases != null && aliases.ContainsKey(terminal))
			return aliases[terminal];
		else if (((StatTokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
			return ((StatTokens)terminal).ToString();
		else
			return CharToString((char)terminal);
	}

}
