// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  LL-GAME
// DateTime: 12/12/2025 1:04:16 AM
// UserName: LaughingLeader
// Input file <C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy - 12/11/2025 11:26:13 PM>

// options: lines

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace LSLib.Stats.Functors
{
public enum FunctorTokens {error=95,EOF=96,
    EXPR_FUNCTORS=97,EXPR_DESCRIPTION_PARAMS=98,IF=99,CONTEXT=100,NAME=101,INTEGER=102,
    TEXT=103,DICE_ROLL=104};

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public partial class FunctorParser: ShiftReduceParser<System.Object, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[57];
  private static State[] states = new State[77];
  private static string[] nonTerms = new string[] {
      "Root", "$accept", "TopLevelFunctors", "OptionalArgs", "TopLevelFunctor", 
      "Contexts", "Condition", "CallOrTextKeyFunctor", "Functors", "Call", "Functor", 
      "ContextList", "Context", "NonEmptyArg", "FunctorName", "OptionalArgList", 
      "Args", "Arg", "ArgStart", "LuaRoot", "ArgEnd", "LuaRootSymbol", "LuaExpr", 
      "LuaSymbol", };

  static FunctorParser() {
    states[0] = new State(new int[]{97,3,98,75},new int[]{-1,1});
    states[1] = new State(new int[]{96,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{100,69,59,-4,96,-4,99,-16,101,-16},new int[]{-3,4,-5,74,-6,7,-12,67,-13,71});
    states[4] = new State(new int[]{59,5,96,-2});
    states[5] = new State(new int[]{100,69,59,-6,96,-6,99,-16,101,-16},new int[]{-5,6,-6,7,-12,67,-13,71});
    states[6] = new State(-7);
    states[7] = new State(new int[]{99,62,101,-21},new int[]{-7,8});
    states[8] = new State(new int[]{101,10},new int[]{-8,9,-10,73,-15,19});
    states[9] = new State(-8);
    states[10] = new State(new int[]{91,11,40,-24,59,-24,96,-24});
    states[11] = new State(new int[]{100,69,93,-11,59,-11,99,-16,101,-16},new int[]{-9,12,-11,72,-6,16,-12,67,-13,71});
    states[12] = new State(new int[]{93,13,59,14});
    states[13] = new State(-9);
    states[14] = new State(new int[]{100,69,93,-13,59,-13,99,-16,101,-16},new int[]{-11,15,-6,16,-12,67,-13,71});
    states[15] = new State(-14);
    states[16] = new State(new int[]{99,62,101,-21},new int[]{-7,17});
    states[17] = new State(new int[]{101,61},new int[]{-10,18,-15,19});
    states[18] = new State(-15);
    states[19] = new State(new int[]{40,21,59,-25,96,-25,93,-25},new int[]{-16,20});
    states[20] = new State(-23);
    states[21] = new State(new int[]{41,-27,101,-34,102,-34,103,-34,100,-34,104,-34,58,-34,33,-34,59,-34,45,-34,40,-34},new int[]{-4,22,-17,24,-14,60,-19,28});
    states[22] = new State(new int[]{41,23});
    states[23] = new State(-26);
    states[24] = new State(new int[]{44,25,41,-28,96,-28});
    states[25] = new State(new int[]{44,-31,41,-31,96,-31,101,-34,102,-34,103,-34,100,-34,104,-34,58,-34,33,-34,59,-34,45,-34,40,-34},new int[]{-18,26,-14,27,-19,28});
    states[26] = new State(-30);
    states[27] = new State(-32);
    states[28] = new State(new int[]{101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,40,57},new int[]{-20,29,-22,56});
    states[29] = new State(new int[]{40,32,101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,-35,41,-35,96,-35},new int[]{-21,30,-22,31});
    states[30] = new State(-33);
    states[31] = new State(-37);
    states[32] = new State(new int[]{41,55,101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,49,40,52},new int[]{-23,33,-24,51,-22,39});
    states[33] = new State(new int[]{41,34,40,36,101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,49},new int[]{-24,35,-22,39});
    states[34] = new State(-38);
    states[35] = new State(-42);
    states[36] = new State(new int[]{41,50,101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,49,40,52},new int[]{-23,37,-24,51,-22,39});
    states[37] = new State(new int[]{41,38,40,36,101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,49},new int[]{-24,35,-22,39});
    states[38] = new State(-43);
    states[39] = new State(-55);
    states[40] = new State(-46);
    states[41] = new State(-47);
    states[42] = new State(-48);
    states[43] = new State(-49);
    states[44] = new State(-50);
    states[45] = new State(-51);
    states[46] = new State(-52);
    states[47] = new State(-53);
    states[48] = new State(-54);
    states[49] = new State(-56);
    states[50] = new State(-45);
    states[51] = new State(-41);
    states[52] = new State(new int[]{101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,49,40,52},new int[]{-23,53,-24,51,-22,39});
    states[53] = new State(new int[]{41,54,40,36,101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,49},new int[]{-24,35,-22,39});
    states[54] = new State(-44);
    states[55] = new State(-39);
    states[56] = new State(-36);
    states[57] = new State(new int[]{101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,49,40,52},new int[]{-23,58,-24,51,-22,39});
    states[58] = new State(new int[]{41,59,40,36,101,40,102,41,103,42,100,43,104,44,58,45,33,46,59,47,45,48,44,49},new int[]{-24,35,-22,39});
    states[59] = new State(-40);
    states[60] = new State(-29);
    states[61] = new State(-24);
    states[62] = new State(new int[]{40,63});
    states[63] = new State(-34,new int[]{-14,64,-19,28});
    states[64] = new State(new int[]{41,65});
    states[65] = new State(new int[]{58,66});
    states[66] = new State(-22);
    states[67] = new State(new int[]{100,69,99,-17,101,-17},new int[]{-13,68});
    states[68] = new State(-19);
    states[69] = new State(new int[]{58,70});
    states[70] = new State(-20);
    states[71] = new State(-18);
    states[72] = new State(-12);
    states[73] = new State(-10);
    states[74] = new State(-5);
    states[75] = new State(new int[]{96,-27,101,-34,102,-34,103,-34,100,-34,104,-34,58,-34,33,-34,59,-34,45,-34,40,-34},new int[]{-4,76,-17,24,-14,60,-19,28});
    states[76] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,96});
    rules[2] = new Rule(-1, new int[]{97,-3});
    rules[3] = new Rule(-1, new int[]{98,-4});
    rules[4] = new Rule(-3, new int[]{});
    rules[5] = new Rule(-3, new int[]{-5});
    rules[6] = new Rule(-3, new int[]{-3,59});
    rules[7] = new Rule(-3, new int[]{-3,59,-5});
    rules[8] = new Rule(-5, new int[]{-6,-7,-8});
    rules[9] = new Rule(-8, new int[]{101,91,-9,93});
    rules[10] = new Rule(-8, new int[]{-10});
    rules[11] = new Rule(-9, new int[]{});
    rules[12] = new Rule(-9, new int[]{-11});
    rules[13] = new Rule(-9, new int[]{-9,59});
    rules[14] = new Rule(-9, new int[]{-9,59,-11});
    rules[15] = new Rule(-11, new int[]{-6,-7,-10});
    rules[16] = new Rule(-6, new int[]{});
    rules[17] = new Rule(-6, new int[]{-12});
    rules[18] = new Rule(-12, new int[]{-13});
    rules[19] = new Rule(-12, new int[]{-12,-13});
    rules[20] = new Rule(-13, new int[]{100,58});
    rules[21] = new Rule(-7, new int[]{});
    rules[22] = new Rule(-7, new int[]{99,40,-14,41,58});
    rules[23] = new Rule(-10, new int[]{-15,-16});
    rules[24] = new Rule(-15, new int[]{101});
    rules[25] = new Rule(-16, new int[]{});
    rules[26] = new Rule(-16, new int[]{40,-4,41});
    rules[27] = new Rule(-4, new int[]{});
    rules[28] = new Rule(-4, new int[]{-17});
    rules[29] = new Rule(-17, new int[]{-14});
    rules[30] = new Rule(-17, new int[]{-17,44,-18});
    rules[31] = new Rule(-18, new int[]{});
    rules[32] = new Rule(-18, new int[]{-14});
    rules[33] = new Rule(-14, new int[]{-19,-20,-21});
    rules[34] = new Rule(-19, new int[]{});
    rules[35] = new Rule(-21, new int[]{});
    rules[36] = new Rule(-20, new int[]{-22});
    rules[37] = new Rule(-20, new int[]{-20,-22});
    rules[38] = new Rule(-20, new int[]{-20,40,-23,41});
    rules[39] = new Rule(-20, new int[]{-20,40,41});
    rules[40] = new Rule(-20, new int[]{40,-23,41});
    rules[41] = new Rule(-23, new int[]{-24});
    rules[42] = new Rule(-23, new int[]{-23,-24});
    rules[43] = new Rule(-23, new int[]{-23,40,-23,41});
    rules[44] = new Rule(-23, new int[]{40,-23,41});
    rules[45] = new Rule(-23, new int[]{-23,40,41});
    rules[46] = new Rule(-22, new int[]{101});
    rules[47] = new Rule(-22, new int[]{102});
    rules[48] = new Rule(-22, new int[]{103});
    rules[49] = new Rule(-22, new int[]{100});
    rules[50] = new Rule(-22, new int[]{104});
    rules[51] = new Rule(-22, new int[]{58});
    rules[52] = new Rule(-22, new int[]{33});
    rules[53] = new Rule(-22, new int[]{59});
    rules[54] = new Rule(-22, new int[]{45});
    rules[55] = new Rule(-24, new int[]{-22});
    rules[56] = new Rule(-24, new int[]{44});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)FunctorTokens.error, (int)FunctorTokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // Root -> EXPR_FUNCTORS, TopLevelFunctors
#line 31 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                      { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 3: // Root -> EXPR_DESCRIPTION_PARAMS, OptionalArgs
#line 32 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                            { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 4: // TopLevelFunctors -> /* empty */
#line 41 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                               { CurrentSemanticValue = MakeFunctorList(); }
#line default
        break;
      case 5: // TopLevelFunctors -> TopLevelFunctor
#line 42 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                   { CurrentSemanticValue = AddFunctor(MakeFunctorList(), ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 7: // TopLevelFunctors -> TopLevelFunctors, ';', TopLevelFunctor
#line 44 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                                        { CurrentSemanticValue = AddFunctor(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 8: // TopLevelFunctor -> Contexts, Condition, CallOrTextKeyFunctor
#line 47 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                                          { CurrentSemanticValue = MakeFunctorOrTextKeyFunctors(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 9: // CallOrTextKeyFunctor -> NAME, '[', Functors, ']'
#line 49 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                             { CurrentSemanticValue = SetTextKey(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-4]); }
#line default
        break;
      case 11: // Functors -> /* empty */
#line 53 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                       { CurrentSemanticValue = MakeFunctorList(); }
#line default
        break;
      case 12: // Functors -> Functor
#line 54 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                   { CurrentSemanticValue = AddFunctor(MakeFunctorList(), ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 14: // Functors -> Functors, ';', Functor
#line 56 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                { CurrentSemanticValue = AddFunctor(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 15: // Functor -> Contexts, Condition, Call
#line 59 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                  { CurrentSemanticValue = MakeFunctor(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 17: // Contexts -> ContextList
#line 62 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                       { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 18: // ContextList -> Context
#line 65 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                      { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 19: // ContextList -> ContextList, Context
#line 66 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                  { CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
#line default
        break;
      case 20: // Context -> CONTEXT, ':'
#line 69 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                      { CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
#line default
        break;
      case 22: // Condition -> IF, '(', NonEmptyArg, ')', ':'
#line 72 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                       { CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
#line default
        break;
      case 23: // Call -> FunctorName, OptionalArgList
#line 75 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                   { CurrentSemanticValue = MakeAction(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 24: // FunctorName -> NAME
#line 77 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                   { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; MarkActionStart(); }
#line default
        break;
      case 25: // OptionalArgList -> /* empty */
#line 79 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                              { CurrentSemanticValue = MakeArgumentList(); }
#line default
        break;
      case 26: // OptionalArgList -> '(', OptionalArgs, ')'
#line 80 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                       { CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
#line default
        break;
      case 27: // OptionalArgs -> /* empty */
#line 83 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                           { CurrentSemanticValue = MakeArgumentList(); }
#line default
        break;
      case 29: // Args -> NonEmptyArg
#line 87 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                   { CurrentSemanticValue = AddArgument(MakeArgumentList(), ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 30: // Args -> Args, ',', Arg
#line 88 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                    { CurrentSemanticValue = AddArgument(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 33: // NonEmptyArg -> ArgStart, LuaRoot, ArgEnd
#line 95 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                                      { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 34: // ArgStart -> /* empty */
#line 97 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                       { InitLiteral(); }
#line default
        break;
      case 35: // ArgEnd -> /* empty */
#line 99 "C:\Projects\CSharp\LSLibNet\src\LSLibStats\Stats\Functor\Functor.yy"
                     { CurrentSemanticValue = MakeLiteral(); }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((FunctorTokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((FunctorTokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
