// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  LL-GAME
// DateTime: 11/29/2025 5:03:57 PM
// UserName: LaughingLeader
// Input file <C:\Projects\CSharp\BG3ModManager\External\lslib\LSLibStats\Stats\Functor\Lua.yy - 12/6/2024 6:12:21 PM>

// options: lines

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace LSLib.Stats.Lua
{
public enum StatLuaTokens {
    error=127,EOF=128,BAD=129,INTEGER=130,FLOAT=131,NAME=132,
    DICE_ROLL=133,BINOP=134,UNOP=135,BIN_OR_UNOP=136,LUA_RESERVED_VAL=137,LITERAL_STRING=138};

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public partial class StatLuaParser: ShiftReduceParser<System.Object, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[42];
  private static State[] states = new State[62];
  private static string[] nonTerms = new string[] {
      "Root", "$accept", "LExp", "LName", "LVar", "LPrefixExp", "LOptionalExpList", 
      "LExpList", "LExpNoUnOp", "LUnOp", "LTableConstructor", "LBinOp", "LFunctionCall", 
      "LArgs", "LOptionalFieldList", "LFieldList", "LField", "LFieldSep", };

  static StatLuaParser() {
    states[0] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-1,1,-3,3,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[1] = new State(new int[]{128,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{134,60,136,61,128,-11,93,-11,41,-11,44,-11,125,-11},new int[]{-12,5});
    states[5] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-3,6,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[6] = new State(-20);
    states[7] = new State(-13);
    states[8] = new State(-14);
    states[9] = new State(-15);
    states[10] = new State(-16);
    states[11] = new State(-17);
    states[12] = new State(new int[]{91,13,58,46,46,58,40,49,123,24,138,57,134,-18,136,-18,128,-18,93,-18,41,-18,44,-18,125,-18},new int[]{-14,45,-11,56});
    states[13] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-3,14,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[14] = new State(new int[]{93,15});
    states[15] = new State(-5);
    states[16] = new State(-21);
    states[17] = new State(-4);
    states[18] = new State(-3);
    states[19] = new State(-22);
    states[20] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-3,21,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[21] = new State(new int[]{41,22});
    states[22] = new State(-23);
    states[23] = new State(-19);
    states[24] = new State(new int[]{91,30,132,18,137,7,130,8,131,9,138,10,133,11,40,20,123,24,135,37,136,38,125,-30},new int[]{-15,25,-16,27,-17,44,-4,39,-3,42,-9,4,-6,12,-5,16,-13,19,-11,23,-10,35});
    states[25] = new State(new int[]{125,26});
    states[26] = new State(-29);
    states[27] = new State(new int[]{44,43,125,-31},new int[]{-18,28});
    states[28] = new State(new int[]{91,30,132,18,137,7,130,8,131,9,138,10,133,11,40,20,123,24,135,37,136,38},new int[]{-17,29,-4,39,-3,42,-9,4,-6,12,-5,16,-13,19,-11,23,-10,35});
    states[29] = new State(-33);
    states[30] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-3,31,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[31] = new State(new int[]{93,32});
    states[32] = new State(new int[]{61,33});
    states[33] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-3,34,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[34] = new State(-34);
    states[35] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-3,36,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[36] = new State(-12);
    states[37] = new State(-40);
    states[38] = new State(-41);
    states[39] = new State(new int[]{61,40,91,-4,58,-4,46,-4,40,-4,123,-4,138,-4,134,-4,136,-4,44,-4,125,-4});
    states[40] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-3,41,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[41] = new State(-35);
    states[42] = new State(-36);
    states[43] = new State(-37);
    states[44] = new State(-32);
    states[45] = new State(-24);
    states[46] = new State(new int[]{132,18},new int[]{-4,47});
    states[47] = new State(new int[]{40,49,123,24,138,57},new int[]{-14,48,-11,56});
    states[48] = new State(-25);
    states[49] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38,41,-7},new int[]{-7,50,-8,52,-3,55,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[50] = new State(new int[]{41,51});
    states[51] = new State(-26);
    states[52] = new State(new int[]{44,53,41,-8});
    states[53] = new State(new int[]{137,7,130,8,131,9,138,10,133,11,132,18,40,20,123,24,135,37,136,38},new int[]{-3,54,-9,4,-6,12,-5,16,-4,17,-13,19,-11,23,-10,35});
    states[54] = new State(-10);
    states[55] = new State(-9);
    states[56] = new State(-27);
    states[57] = new State(-28);
    states[58] = new State(new int[]{132,18},new int[]{-4,59});
    states[59] = new State(-6);
    states[60] = new State(-38);
    states[61] = new State(-39);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,128});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-4, new int[]{132});
    rules[4] = new Rule(-5, new int[]{-4});
    rules[5] = new Rule(-5, new int[]{-6,91,-3,93});
    rules[6] = new Rule(-5, new int[]{-6,46,-4});
    rules[7] = new Rule(-7, new int[]{});
    rules[8] = new Rule(-7, new int[]{-8});
    rules[9] = new Rule(-8, new int[]{-3});
    rules[10] = new Rule(-8, new int[]{-8,44,-3});
    rules[11] = new Rule(-3, new int[]{-9});
    rules[12] = new Rule(-3, new int[]{-10,-3});
    rules[13] = new Rule(-9, new int[]{137});
    rules[14] = new Rule(-9, new int[]{130});
    rules[15] = new Rule(-9, new int[]{131});
    rules[16] = new Rule(-9, new int[]{138});
    rules[17] = new Rule(-9, new int[]{133});
    rules[18] = new Rule(-9, new int[]{-6});
    rules[19] = new Rule(-9, new int[]{-11});
    rules[20] = new Rule(-9, new int[]{-9,-12,-3});
    rules[21] = new Rule(-6, new int[]{-5});
    rules[22] = new Rule(-6, new int[]{-13});
    rules[23] = new Rule(-6, new int[]{40,-3,41});
    rules[24] = new Rule(-13, new int[]{-6,-14});
    rules[25] = new Rule(-13, new int[]{-6,58,-4,-14});
    rules[26] = new Rule(-14, new int[]{40,-7,41});
    rules[27] = new Rule(-14, new int[]{-11});
    rules[28] = new Rule(-14, new int[]{138});
    rules[29] = new Rule(-11, new int[]{123,-15,125});
    rules[30] = new Rule(-15, new int[]{});
    rules[31] = new Rule(-15, new int[]{-16});
    rules[32] = new Rule(-16, new int[]{-17});
    rules[33] = new Rule(-16, new int[]{-16,-18,-17});
    rules[34] = new Rule(-17, new int[]{91,-3,93,61,-3});
    rules[35] = new Rule(-17, new int[]{-4,61,-3});
    rules[36] = new Rule(-17, new int[]{-3});
    rules[37] = new Rule(-18, new int[]{44});
    rules[38] = new Rule(-12, new int[]{134});
    rules[39] = new Rule(-12, new int[]{136});
    rules[40] = new Rule(-10, new int[]{135});
    rules[41] = new Rule(-10, new int[]{136});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)StatLuaTokens.error, (int)StatLuaTokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((StatLuaTokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((StatLuaTokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
