// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  LL-GAME
// DateTime: 11/29/2025 5:03:57 PM
// UserName: LaughingLeader
// Input file <C:\Projects\CSharp\BG3ModManager\External\lslib\LSLibStats\Stats\Functor\Requirement.yy - 12/6/2024 6:12:21 PM>

// options: lines

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace LSLib.Stats.Requirements
{
public enum RequirementTokens {
    error=61,EOF=62,NAME=63,INTEGER=64,TEXT=65};

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public partial class RequirementParser: ShiftReduceParser<System.Object, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[11];
  private static State[] states = new State[12];
  private static string[] nonTerms = new string[] {
      "Root", "$accept", "Requirements", "UnaryRequirement", "Requirement", };

  static RequirementParser() {
    states[0] = new State(new int[]{63,7,33,9,59,-3,62,-3},new int[]{-1,1,-3,3,-4,11,-5,6});
    states[1] = new State(new int[]{62,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{59,4,62,-2});
    states[4] = new State(new int[]{63,7,33,9,59,-5,62,-5},new int[]{-4,5,-5,6});
    states[5] = new State(-6);
    states[6] = new State(-7);
    states[7] = new State(new int[]{64,8,59,-9,62,-9});
    states[8] = new State(-10);
    states[9] = new State(new int[]{63,7},new int[]{-5,10});
    states[10] = new State(-8);
    states[11] = new State(-4);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,62});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{});
    rules[4] = new Rule(-3, new int[]{-4});
    rules[5] = new Rule(-3, new int[]{-3,59});
    rules[6] = new Rule(-3, new int[]{-3,59,-4});
    rules[7] = new Rule(-4, new int[]{-5});
    rules[8] = new Rule(-4, new int[]{33,-5});
    rules[9] = new Rule(-5, new int[]{63});
    rules[10] = new Rule(-5, new int[]{63,64});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)RequirementTokens.error, (int)RequirementTokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 3: // Requirements -> /* empty */
#line 27 "C:\Projects\CSharp\BG3ModManager\External\lslib\LSLibStats\Stats\Functor\Requirement.yy"
                           { CurrentSemanticValue = MakeRequirements(); }
#line default
        break;
      case 4: // Requirements -> UnaryRequirement
#line 28 "C:\Projects\CSharp\BG3ModManager\External\lslib\LSLibStats\Stats\Functor\Requirement.yy"
                                { CurrentSemanticValue = AddRequirement(MakeRequirements(), ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 6: // Requirements -> Requirements, ';', UnaryRequirement
#line 30 "C:\Projects\CSharp\BG3ModManager\External\lslib\LSLibStats\Stats\Functor\Requirement.yy"
                                                 { CurrentSemanticValue = AddRequirement(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 8: // UnaryRequirement -> '!', Requirement
#line 34 "C:\Projects\CSharp\BG3ModManager\External\lslib\LSLibStats\Stats\Functor\Requirement.yy"
                                   { CurrentSemanticValue = MakeNotRequirement(ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 9: // Requirement -> NAME
#line 37 "C:\Projects\CSharp\BG3ModManager\External\lslib\LSLibStats\Stats\Functor\Requirement.yy"
                   { CurrentSemanticValue = MakeRequirement(ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 10: // Requirement -> NAME, INTEGER
#line 38 "C:\Projects\CSharp\BG3ModManager\External\lslib\LSLibStats\Stats\Functor\Requirement.yy"
                           { CurrentSemanticValue = MakeIntRequirement(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((RequirementTokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((RequirementTokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
